"""add_portal_insurance_discharge_structured_labs

Revision ID: e15ec6a400f1
Revises: f2b8fd2fe268
Create Date: 2026-09-23 20:54:00.782986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15ec6a400f1'
down_revision: Union[str, None] = 'f2b8fd2fe268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('tpa_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_insurance_providers_code'), 'insurance_providers', ['code'], unique=True)
    op.create_table('lab_test_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_low', sa.Float(), nullable=True),
    sa.Column('reference_high', sa.Float(), nullable=True),
    sa.Column('reference_text', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_numeric', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_test_components_test_id'), 'lab_test_components', ['test_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('member_id', sa.String(length=100), nullable=True),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['insurance_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_patient_id'), 'insurance_policies', ['patient_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_policy_number'), 'insurance_policies', ['policy_number'], unique=True)
    op.create_table('patient_portal_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_portal_links_patient_id'), 'patient_portal_links', ['patient_id'], unique=True)
    op.create_index(op.f('ix_patient_portal_links_user_id'), 'patient_portal_links', ['user_id'], unique=True)
    op.create_table('discharges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admission_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('attending_doctor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('discharge_reason', sa.String(length=255), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('pending_results_checked', sa.Boolean(), nullable=False),
    sa.Column('billing_cleared', sa.Boolean(), nullable=False),
    sa.Column('insurance_cleared', sa.Boolean(), nullable=False),
    sa.Column('initiated_by_id', sa.String(length=36), nullable=False),
    sa.Column('approved_by_id', sa.String(length=36), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharges_admission_id'), 'discharges', ['admission_id'], unique=True)
    op.create_index(op.f('ix_discharges_patient_id'), 'discharges', ['patient_id'], unique=False)
    op.create_index(op.f('ix_discharges_status'), 'discharges', ['status'], unique=False)
    op.create_table('preauthorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('admission_id', sa.String(length=36), nullable=True),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preauthorizations_patient_id'), 'preauthorizations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_preauthorizations_policy_id'), 'preauthorizations', ['policy_id'], unique=False)
    op.create_index(op.f('ix_preauthorizations_request_number'), 'preauthorizations', ['request_number'], unique=True)
    op.create_index(op.f('ix_preauthorizations_status'), 'preauthorizations', ['status'], unique=False)
    op.create_table('discharge_instructions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discharge_id', sa.String(length=36), nullable=False),
    sa.Column('instruction_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['discharge_id'], ['discharges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharge_instructions_discharge_id'), 'discharge_instructions', ['discharge_id'], unique=False)
    op.create_table('discharge_medications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discharge_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discharge_id'], ['discharges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discharge_medications_discharge_id'), 'discharge_medications', ['discharge_id'], unique=False)
    op.create_table('insurance_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('admission_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('rejected_amount', sa.Float(), nullable=False),
    sa.Column('documents_json', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_claim_number'), 'insurance_claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_insurance_claims_patient_id'), 'insurance_claims', ['patient_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_policy_id'), 'insurance_claims', ['policy_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_status'), 'insurance_claims', ['status'], unique=False)
    op.create_table('lab_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_order_items_order_id'), 'lab_order_items', ['order_id'], unique=False)
    op.create_table('insurance_claim_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_item_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('claimed_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('rejected_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['insurance_claims.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claim_items_claim_id'), 'insurance_claim_items', ['claim_id'], unique=False)
    op.create_table('lab_result_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('value_text', sa.String(length=255), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['lab_test_components.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['lab_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_result_values_result_id'), 'lab_result_values', ['result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_result_values_result_id'), table_name='lab_result_values')
    op.drop_table('lab_result_values')
    op.drop_index(op.f('ix_insurance_claim_items_claim_id'), table_name='insurance_claim_items')
    op.drop_table('insurance_claim_items')
    op.drop_index(op.f('ix_lab_order_items_order_id'), table_name='lab_order_items')
    op.drop_table('lab_order_items')
    op.drop_index(op.f('ix_insurance_claims_status'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_policy_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_patient_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_claim_number'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_discharge_medications_discharge_id'), table_name='discharge_medications')
    op.drop_table('discharge_medications')
    op.drop_index(op.f('ix_discharge_instructions_discharge_id'), table_name='discharge_instructions')
    op.drop_table('discharge_instructions')
    op.drop_index(op.f('ix_preauthorizations_status'), table_name='preauthorizations')
    op.drop_index(op.f('ix_preauthorizations_request_number'), table_name='preauthorizations')
    op.drop_index(op.f('ix_preauthorizations_policy_id'), table_name='preauthorizations')
    op.drop_index(op.f('ix_preauthorizations_patient_id'), table_name='preauthorizations')
    op.drop_table('preauthorizations')
    op.drop_index(op.f('ix_discharges_status'), table_name='discharges')
    op.drop_index(op.f('ix_discharges_patient_id'), table_name='discharges')
    op.drop_index(op.f('ix_discharges_admission_id'), table_name='discharges')
    op.drop_table('discharges')
    op.drop_index(op.f('ix_patient_portal_links_user_id'), table_name='patient_portal_links')
    op.drop_index(op.f('ix_patient_portal_links_patient_id'), table_name='patient_portal_links')
    op.drop_table('patient_portal_links')
    op.drop_index(op.f('ix_insurance_policies_policy_number'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_patient_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_lab_test_components_test_id'), table_name='lab_test_components')
    op.drop_table('lab_test_components')
    op.drop_index(op.f('ix_insurance_providers_code'), table_name='insurance_providers')
    op.drop_table('insurance_providers')
    # ### end Alembic commands ###
