import { useMutation, useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import api from '../lib/api'
import { Brain, Sparkles, AlertTriangle } from 'lucide-react'

export default function AIRoadmapPage() {
  const [patientId, setPatientId] = useState('')
  const { data: patients = [] } = useQuery({ queryKey: ['ai-patients'], queryFn: () => api.get('/patients?limit=100').then(r => r.data) })
  const risk = useMutation({ mutationFn: () => api.post('/ai/patient-risk', { patient_id: patientId }).then(r => r.data) })
  const los = useMutation({ mutationFn: () => api.post('/ai/length-of-stay', { patient_id: patientId }).then(r => r.data) })
  const readmission = useMutation({ mutationFn: () => api.post('/ai/readmission-risk', { patient_id: patientId }).then(r => r.data) })
  const result = risk.data
  return <div className="space-y-5">
    <div className="card p-6 border-l-4 border-blue-600"><div className="flex gap-3"><Brain className="text-blue-700"/><div><h1 className="text-xl font-bold">AI decision support</h1><p className="text-sm text-gray-600 mt-1">Versioned models trained explicitly on synthetic demonstration data. Predictions are generated from persisted patient vitals, conditions and compatible structured labs.</p></div></div></div>
    <section className="card p-5"><h2 className="text-sm font-semibold mb-3">Patient risk and care-planning signals</h2><div className="flex gap-3 items-end"><label className="text-sm flex-1">Patient<select className="block border rounded px-2 py-2 mt-1 w-full" value={patientId} onChange={e => setPatientId(e.target.value)}><option value="">Select a patient</option>{patients.map((patient: any) => <option key={patient.id} value={patient.id}>{patient.patient_id} — {patient.full_name}</option>)}</select></label><button disabled={!patientId || risk.isPending} onClick={() => risk.mutate()} className="btn-primary text-sm">Run risk model</button><button disabled={!patientId || los.isPending} onClick={() => los.mutate()} className="btn-secondary text-sm">Estimate LOS</button><button disabled={!patientId || readmission.isPending} onClick={() => readmission.mutate()} className="btn-secondary text-sm">Readmission risk</button></div>{(risk.isError || los.isError || readmission.isError) && <p className="text-sm text-red-600 mt-3">Unable to obtain a prediction. Confirm trained artifacts and patient access.</p>}</section>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{result && <div className="card p-5"><p className="text-xs text-gray-500">Patient deterioration risk</p><p className="text-2xl font-bold mt-2">{result.risk_category}</p><p className="text-sm mt-1">Probability: {Math.round(result.risk_probability * 100)}%</p><p className="text-xs text-gray-500 mt-3">{result.model.algorithm} · v{result.model.model_version}</p></div>}{los.data && <div className="card p-5"><p className="text-xs text-gray-500">Estimated inpatient length of stay</p><p className="text-2xl font-bold mt-2">{los.data.estimated_days} days</p><p className="text-xs text-gray-500 mt-3">Synthetic/demo data only</p></div>}{readmission.data && <div className="card p-5"><p className="text-xs text-gray-500">Readmission risk</p><p className="text-2xl font-bold mt-2">{readmission.data.risk_category}</p><p className="text-sm mt-1">Probability: {Math.round(readmission.data.readmission_probability * 100)}%</p></div>}</div>
    <div className="rounded border border-amber-200 bg-amber-50 p-4 flex gap-2 text-sm text-amber-900"><AlertTriangle size={18} className="shrink-0"/><span>AI-generated decision support. Not a diagnosis. Human review required. These tools do not prescribe, discharge, approve claims, or take any autonomous action.</span></div>
    <section className="card p-5"><div className="flex gap-2 items-center"><Sparkles size={16} className="text-blue-700"/><h2 className="text-sm font-semibold">Available model artifacts</h2></div><p className="text-sm text-gray-600 mt-2">Patient deterioration, length of stay, readmission risk, bed occupancy, and pharmacy demand are persisted as joblib artifacts with versioned JSON metadata under <code>backend/ml</code>. Bed and pharmacy endpoints are available to the operations screens/API.</p></section>
  </div>
}
