import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import api from '../lib/api'

export default function InsurancePage() {
  const client = useQueryClient(); const [patientId, setPatientId] = useState(''); const [providerId, setProviderId] = useState(''); const [policyNumber, setPolicyNumber] = useState('')
  const { data: patients = [] } = useQuery({ queryKey: ['insurance-patients'], queryFn: () => api.get('/patients?limit=200').then(r => r.data) })
  const { data: providers = [] } = useQuery({ queryKey: ['insurance-providers'], queryFn: () => api.get('/insurance/providers').then(r => r.data) })
  const { data: policies = [] } = useQuery({ queryKey: ['insurance-policies'], queryFn: () => api.get('/insurance/policies').then(r => r.data) })
  const { data: claims = [] } = useQuery({ queryKey: ['insurance-claims'], queryFn: () => api.get('/insurance/claims').then(r => r.data) })
  const createPolicy = useMutation({ mutationFn: () => api.post('/insurance/policies', { patient_id: patientId, provider_id: providerId, policy_number: policyNumber, coverage_amount: 250000, valid_from: '2026-01-01', valid_to: '2026-12-31' }), onSuccess: () => client.invalidateQueries({ queryKey: ['insurance-policies'] }) })
  return <div className="space-y-5"><div><h1 className="text-xl font-bold">Insurance / TPA</h1><p className="text-sm text-gray-500">Persisted policy, claim and preauthorization workflow</p></div><section className="card p-5"><h2 className="text-sm font-semibold mb-3">Register insurance policy</h2><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><select className="border rounded px-2 py-2 text-sm" value={patientId} onChange={e => setPatientId(e.target.value)}><option value="">Patient</option>{patients.map((p: any) => <option key={p.id} value={p.id}>{p.patient_id} — {p.full_name}</option>)}</select><select className="border rounded px-2 py-2 text-sm" value={providerId} onChange={e => setProviderId(e.target.value)}><option value="">Provider</option>{providers.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="border rounded px-2 py-2 text-sm" placeholder="Policy number" value={policyNumber} onChange={e => setPolicyNumber(e.target.value)}/><button disabled={!patientId || !providerId || !policyNumber} onClick={() => createPolicy.mutate()} className="btn-primary text-sm">Save policy</button></div>{createPolicy.isError && <p className="text-xs text-red-600 mt-2">Policy could not be saved; verify unique policy number and valid dates.</p>}</section><section className="card overflow-hidden"><div className="px-5 py-4 border-b"><h2 className="text-sm font-semibold">Policies</h2></div><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="table-th">Patient</th><th className="table-th">Provider</th><th className="table-th">Policy</th><th className="table-th">Coverage</th><th className="table-th">Status</th></tr></thead><tbody>{policies.map((p: any) => <tr key={p.id}><td className="table-td">{p.patient_name}</td><td className="table-td">{p.provider}</td><td className="table-td font-mono">{p.policy_number}</td><td className="table-td">₹{p.coverage_amount}</td><td className="table-td"><span className="badge badge-success">{p.status}</span></td></tr>)}</tbody></table></section><section className="card overflow-hidden"><div className="px-5 py-4 border-b"><h2 className="text-sm font-semibold">Claims</h2></div><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="table-th">Claim</th><th className="table-th">Patient</th><th className="table-th">Submitted</th><th className="table-th">Approved</th><th className="table-th">Status</th></tr></thead><tbody>{claims.map((c: any) => <tr key={c.id}><td className="table-td font-mono">{c.claim_number}</td><td className="table-td">{c.patient_name}</td><td className="table-td">₹{c.submitted_amount}</td><td className="table-td">₹{c.approved_amount}</td><td className="table-td">{c.status}</td></tr>)}{claims.length === 0 && <tr><td colSpan={5} className="table-td text-center text-gray-500">No claims yet.</td></tr>}</tbody></table></section></div>
}
