import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router-dom'
import { AlertCircle, ChevronLeft, ChevronRight, Search, UserPlus, X } from 'lucide-react'
import api from '../lib/api'
import clsx from 'clsx'

const message = (error: any) => error?.response?.data?.detail || error?.message || 'The request could not be completed.'

export default function PatientsPage() {
  const navigate = useNavigate(); const [q, setQ] = useState(''); const [page, setPage] = useState(1); const [status, setStatus] = useState(''); const [registering, setRegistering] = useState(false)
  const limit = 15
  const { data = [], isLoading, error } = useQuery({ queryKey: ['patients', page, q, status], queryFn: () => api.get('/patients', { params: { q: q || undefined, status_filter: status || undefined, offset: (page - 1) * limit, limit } }).then(r => r.data), placeholderData: old => old })
  const patients = Array.isArray(data) ? data : data.items || []
  return <div className="space-y-4">
    <div className="flex items-center justify-between"><div><h1 className="text-xl font-bold">Patient Registry</h1><p className="text-sm text-gray-500">Search by hospital ID, name, or mobile.</p></div><button className="btn-primary flex items-center gap-2" onClick={() => setRegistering(true)}><UserPlus size={15}/>Register Patient</button></div>
    <div className="card px-4 py-3 flex flex-wrap gap-3"><div className="relative flex-1 min-w-64"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input className="input pl-8" placeholder="Patient ID, name, or mobile…" value={q} onChange={e => { setQ(e.target.value); setPage(1) }}/></div>{[['','All'],['ADMITTED','Admitted'],['OUTPATIENT','Outpatient']].map(([value,label]) => <button key={value} onClick={() => {setStatus(value);setPage(1)}} className={clsx('px-3 py-1 text-xs rounded border', status === value ? 'bg-blue-700 text-white border-blue-700' : 'border-gray-300 text-gray-600')}>{label}</button>)}</div>
    <section className="card overflow-hidden">{error ? <Error text={message(error)}/> : isLoading ? <p className="p-8 text-center text-gray-500">Loading patients…</p> : <table className="w-full"><thead className="bg-gray-50"><tr><th className="table-th">Patient ID</th><th className="table-th">Name</th><th className="table-th">Age / Gender</th><th className="table-th">Mobile</th><th className="table-th">Admission</th><th className="table-th">Registered</th></tr></thead><tbody className="divide-y divide-gray-100">{patients.map((p:any) => <tr key={p.id} className="hover:bg-blue-50 cursor-pointer" onClick={() => navigate('/patients/' + p.id)}><td className="table-td font-mono text-xs text-blue-700">{p.patient_id}</td><td className="table-td"><p className="font-medium">{p.full_name}</p><p className="text-xs text-gray-400">{p.blood_group || 'Blood group not recorded'}</p></td><td className="table-td">{p.age} / {p.gender}</td><td className="table-td">{p.mobile}</td><td className="table-td"><span className={clsx('badge', p.current_status === 'ADMITTED' ? 'badge-info' : 'badge-gray')}>{p.current_status}</span></td><td className="table-td text-xs">{new Date(p.created_at).toLocaleDateString('en-IN')}</td></tr>)}{patients.length === 0 && <tr><td colSpan={6} className="table-td text-center text-gray-500 py-8">No patients found.</td></tr>}</tbody></table>}<div className="flex justify-between p-3 border-t"><span className="text-xs text-gray-500">Showing {patients.length} records</span><div><button onClick={() => setPage(Math.max(1,page-1))} disabled={page===1} className="p-1 disabled:opacity-40"><ChevronLeft size={16}/></button><button onClick={() => setPage(page+1)} disabled={patients.length < limit} className="p-1 disabled:opacity-40"><ChevronRight size={16}/></button></div></div></section>
    {registering && <RegistrationModal onClose={() => setRegistering(false)} onCreated={id => navigate('/patients/' + id)}/>}</div>
}

export function Error({ text }: { text: string }) { return <div className="m-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700 flex gap-2"><AlertCircle size={16}/>{text}</div> }

export function RegistrationModal({ onClose, onCreated }: { onClose: () => void, onCreated: (id: string) => void }) {
  const client = useQueryClient(); const [form, setForm] = useState<any>({ first_name:'', last_name:'', date_of_birth:'', gender:'', mobile:'', email:'', address:'', registered_branch_id:'', emergency_name:'', emergency_phone:'', emergency_relationship:'OTHER' }); const [failure,setFailure] = useState('')
  const { data: branches = [] } = useQuery({ queryKey:['branches'], queryFn: () => api.get('/organization/branches').then(r=>r.data) })
  const create = useMutation({ mutationFn: (payload:any) => api.post('/patients', payload).then(r=>r.data), onSuccess: patient => { client.invalidateQueries({queryKey:['patients']}); client.invalidateQueries({queryKey:['dashboard-summary']}); onCreated(patient.id) }, onError: err => setFailure(message(err)) })
  const submit = (e: React.FormEvent) => { e.preventDefault(); setFailure(''); if (!form.registered_branch_id) return setFailure('Select the registering branch.'); const payload:any = { first_name:form.first_name, last_name:form.last_name, date_of_birth:form.date_of_birth, gender:form.gender, mobile:form.mobile, registered_branch_id:form.registered_branch_id, email:form.email || undefined, address:form.address || undefined }; if (form.emergency_name || form.emergency_phone) payload.emergency_contact = { name:form.emergency_name, phone:form.emergency_phone, relationship_type:form.emergency_relationship, is_primary:true }; create.mutate(payload) }
  const field = (name:string, label:string, type='text', required=false) => <label className="text-sm"><span className="block mb-1 text-gray-700">{label}{required && ' *'}</span><input type={type} required={required} className="input" value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>
  return <div className="fixed inset-0 z-50 bg-black/50 grid place-items-center p-4"><form onSubmit={submit} className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-auto"><div className="p-5 border-b flex justify-between"><div><h2 className="font-semibold text-lg">Register Patient</h2><p className="text-xs text-gray-500">Creates the patient, registration event and audit record.</p></div><button type="button" onClick={onClose}><X size={18}/></button></div><div className="p-5 grid grid-cols-1 sm:grid-cols-2 gap-4">{failure && <div className="sm:col-span-2"><Error text={failure}/></div>}{field('first_name','First name','text',true)}{field('last_name','Last name','text',true)}{field('date_of_birth','Date of birth','date',true)}<label className="text-sm"><span className="block mb-1 text-gray-700">Gender *</span><select required className="input" value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option value="">Select…</option><option>MALE</option><option>FEMALE</option><option>OTHER</option></select></label>{field('mobile','Mobile','tel',true)}{field('email','Email','email')}<label className="text-sm sm:col-span-2"><span className="block mb-1 text-gray-700">Address</span><input className="input" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="text-sm sm:col-span-2"><span className="block mb-1 text-gray-700">Registering branch *</span><select required className="input" value={form.registered_branch_id} onChange={e=>setForm({...form,registered_branch_id:e.target.value})}><option value="">Select branch…</option>{branches.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><p className="sm:col-span-2 text-sm font-semibold text-gray-700 pt-1">Emergency contact</p>{field('emergency_name','Name')}{field('emergency_phone','Mobile','tel')}<label className="text-sm"><span className="block mb-1 text-gray-700">Relationship</span><input className="input" value={form.emergency_relationship} onChange={e=>setForm({...form,emergency_relationship:e.target.value})}/></label></div><div className="p-5 border-t flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button disabled={create.isPending} className="btn-primary">{create.isPending ? 'Registering…' : 'Register & open Patient 360'}</button></div></form></div>
}
